import { Task } from "./TasksTable";

export const TASKS_DATA: Task[] = [
    {
        id: "1",
        title: "Redesign landing page hero section",
        tag: "Marketing Website",
        status: "In Progress",
        priority: "High",
        assignees: 2,
        estHours: "12 hrs",
        deadline: "Today, 5:00 PM",
        progressText: "4/8 Completed",
        progressValue: 50,
    },
    {
        id: "2",
        title: "Fix authentication bug in mobile app",
        tag: "Mobile App",
        status: "Blocked",
        priority: "Critical",
        assignees: 1,
        estHours: "6 hrs",
        deadline: "2 days overdue",
        progressText: "1/3 Completed",
        progressValue: 33,
    },
    {
        id: "3",
        title: "Create Q4 marketing campaign assets",
        tag: "Marketing",
        status: "To Do",
        priority: "Medium",
        assignees: 3,
        estHours: "20 hrs",
        deadline: "Dec 15, 2024",
        progressText: "0/12 Completed",
        progressValue: 0,
    },
    {
        id: "4",
        title: "Update API documentation",
        tag: "Backend",
        status: "Ready for Review",
        priority: "Low",
        assignees: 1,
        estHours: "4 hrs",
        deadline: "Dec 10, 2024",
        progressText: "5/5 Completed",
        progressValue: 100,
    },
    {
        id: "5",
        title: "Conduct user research interviews",
        tag: "Research",
        status: "Done",
        priority: "High",
        assignees: 2,
        estHours: "15 hrs",
        deadline: "Completed",
        progressText: "10/10 Completed",
        progressValue: 100,
    },
];
